### ISSUE TITLE
Evaluation when reducing text token

### ISSUE THREAD

**Issue by MingliangLiang3** [UCSC-VLAA/CLIPA#12]
Thanks for your work. I would like to know how to evaluate the performance on ImageNet when pre-training the model with reduced text tokens before fine-tuning. Because reducing text tokens breaks templates and class names, especially when using shorter text tokens (4 or 8).

**Comment by Anastasiais-ml** [comment]
I find this in your paper: "Note that the pre-training performance is noticeably lower for input texts with a length smaller than 8. This is because the prompt templates we used for evaluation are often longer than a text length of 8."
So, when you evaluate the model, you still reduce the length of the template and class name to a fixed value, right?
