### ISSUE TITLE
What's the lr for ViT-H/14 in pre-training

### ISSUE THREAD

**Issue by viyjy** [UCSC-VLAA/CLIPA#9]
Hi, thanks for your great work.
The paper said that the lr is 8e-6 * (batch_size/256). However, I found several different version in your code.
For example, https://github.com/UCSC-VLAA/CLIPA/blob/master/clipa_torch/scripts/exp/tpu/vit_h14/i36_t8_pretrain.sh#L19
and config.json in https://drive.google.com/drive/folders/1xSxdNZFg2Vhun5898fQdDxGG8c8ex-wm

I am using GPU for the training, may I ask what's the correct lr should be used for ViT-H/14? Thanks.

**Comment by zw615** [comment]
Hi, sorry for the late reply! I double checked the _pretrain.sh_ file you mentioned. Please note that the `--batch-size` argument in the file actually means the batch size on a single device. Since the file is meant to be used on a TPU v3-256 machine, the lr should be _8e-6 * (256 * 256) / 256_, which is indeed _2.048e-3_.
